version: "3.8"
services:
  recommender:
    build: .
    container_name: streamlit_recommender
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      - DB_URI=postgresql://TIKITAKA:TIKITAKA@TIKITAKA_postgres:5432/TIKITAKA_DB
    networks:
      - shopping-network
    restart: unless-stopped

networks:
  shopping-network:
    external: true