version: "3.8"
services:
  recommender:
    build: .
    container_name: streamlit_recommender
    ports:
      - "8501:8501"
    environment:
      - DB_URI=postgresql://TIKITAKA:TIKITAKA@TIKITAKA_postgres:5432/TIKITAKA_DB
    networks:
      - my_pg_net
    restart: unless-stopped

networks:
  my_pg_net:
    external: true